Feat/NET097-1/add_user_roles
IT-Academy-Social-Projects-KRV/MilitaryManager pull request #1
Opened 2022-08-24 09:09 UTC by 5haki6

2022-08-29 09:04 UTC, vladtymo requested changes
The realisation looks good, but there are a few spacing and alignment mistakes. Please, fix them and commit the changes.

2022-08-29 09:04 UTC, vladtymo commented on MilitaryManager.IdentityServer/Controllers/AccountController.cs
> +        //
Fix the code alignment here and in other places.

2022-08-29 09:04 UTC, vladtymo commented on MilitaryManager.IdentityServer/Startup.cs
> +
You can write only a one empty line for spacing. Please, don't leave empty blocks.

2022-09-05 06:02 UTC, vladtymo approved these changes

2022-09-05 06:36 UTC, Alex-knu approved these changes

2022-09-05 06:39 UTC, merged