Feat/net097 13/add azure blob
IT-Academy-Social-Projects-KRV/MilitaryManager pull request #17
Opened 2022-10-01 16:47 UTC by 5haki6

2022-10-01 18:47 UTC, Alex-knu requested changes

2022-10-01 18:47 UTC, Alex-knu commented on MilitaryManager.Attachments.API/wwwroot/documents/3123.txt
> +Test file )
Remove all files from wwwroot. it`s test data

2022-10-01 18:47 UTC, Alex-knu commented on MilitaryManager.Attachments.API/StoreConfig/StoreModeConfig.cs
> +
Move this file to Infrastructure. Meybe it`s better because this logic for work with global services. Need discuss

2022-10-01 18:47 UTC, Alex-knu commented on MilitaryManager.Attachments.API/Services/StoreService/StoreService.cs
> +
Move this file to Core or Infrastructure. Meybe it`s better because this logic for work with global services. Need discuss

2022-10-01 18:47 UTC, Alex-knu commented on MilitaryManager.Attachments.API/Services/StoreService/LocalStoreService.cs
> +
Move this file to Core.

2022-10-01 18:47 UTC, Alex-knu commented on MilitaryManager.Attachments.API/Services/StoreService/IStoreService.cs
> +
Move this file to Core.

2022-10-01 18:47 UTC, Alex-knu commented on MilitaryManager.Attachments.API/Services/StoreService/DockerContainerStoreService.cs
> +{
Move this file to Core.

2022-10-01 18:47 UTC, Alex-knu commented on MilitaryManager.Attachments.API/Services/StoreService/AzureStoreService.cs
> +
Move this file to Core.

2022-10-01 18:47 UTC, Alex-knu commented on MilitaryManager.Attachments.API/Models/FileModel.cs
> +
Move this file to Core.

2022-10-01 18:47 UTC, Alex-knu commented on MilitaryManager.Attachments.API/Controllers/AttachmentsController.cs
> +        [HttpPost]
The path is incorrect. We cannot use this implementation in Angular. Change it to [Route("{id}")] or don't specify the path at all. To understand how we use controllers look at Angular base.services.ts lines 81-87, 106-144

2022-10-03 17:57 UTC, Alex-knu requested changes

2022-10-03 17:57 UTC, Alex-knu commented on MilitaryManager.IdentityServer/Startup.cs
> -
?

2022-10-03 17:57 UTC, Alex-knu commented on docker-compose.override.yml
> +     - 11002:11002
Change ports

2022-10-03 17:57 UTC, Alex-knu commented on docker-compose.yml
> +      - 11002:11002
Ports

2022-10-03 17:57 UTC, Alex-knu commented on MilitaryManager.Attachments.API/Controllers/AttachmentsController.cs
> +            )
?

2022-10-03 18:02 UTC, Alex-knu commented on MilitaryManager.Attachments.API/Startup.cs
> +
remove emty line

2022-10-03 18:02 UTC, Alex-knu commented on MilitaryManager.Attachments.API/Controllers/AttachmentsController.cs
> +
remove emty line

2022-10-04 17:17 UTC, Alex-knu approved these changes

2022-10-05 07:13 UTC, vladtymo approved these changes

2022-10-06 06:40 UTC, merged