Feat/17/UI for documents
IT-Academy-Social-Projects-KRV/MilitaryManager pull request #28
Opened 2022-10-07 13:51 UTC by Zakerman110

2022-10-10 13:07 UTC, Alex-knu requested changes

2022-10-10 13:07 UTC, Alex-knu commented on MilitaryManager/client-app/src/app/components/document/document.component.ts
> +    // this.tabs.push('Новий документ ' + (this.tabs.length + 1));
Remove comments

2022-10-10 13:07 UTC, Alex-knu commented on MilitaryManager/client-app/src/app/components/document/document.component.ts
> +            //this.progress = Math.round((100 * event.loaded) / event.total);
Remove comments

2022-10-10 13:07 UTC, Alex-knu commented on MilitaryManager/client-app/src/app/components/document/document.component.ts
> +            //this.message = 'Download success.';
Remove comments

2022-10-10 13:07 UTC, Alex-knu commented on MilitaryManager/client-app/src/app/components/document/document.component.ts
> +            //this.message = 'Download success.';
Remove

2022-10-10 13:12 UTC, Alex-knu requested changes

2022-10-10 13:12 UTC, Alex-knu commented on MilitaryManager/client-app/src/app/shared/services/api/decree.service.ts
> +    return this.httpClient.put(`${this.single.baseUrl}pdfs`, formData, { reportProgress: true, observe: 'events' })
Create PdfService for PdfController and use it

2022-10-10 13:12 UTC, Alex-knu commented on MilitaryManager/client-app/src/app/shared/services/api/decree.service.ts
> +    return this.httpClient.get(`${this.single.baseUrl}pdfs/${id}`, {
Create PdfService for PdfController and use it

2022-10-10 13:12 UTC, Alex-knu commented on MilitaryManager/client-app/src/app/shared/services/api/decree.service.ts
> +    return this.httpClient.get(`${this.single.baseUrl}pdfs/signed/${id}`, {
Create PdfService for PdfController and use it

2022-10-11 16:10 UTC, Alex-knu approved these changes

2022-10-12 08:53 UTC, vladtymo commented on MilitaryManager/client-app/src/app/modules/attachments-module/pages/decree-new/decree-new.component.ts
> +  //@ts-ignore
Consider configuring null checks in **tsconfig.json** instead of putting `//@ts-ignore` above each line.

2022-10-12 18:26 UTC, 5haki6 approved these changes

2022-10-12 18:27 UTC, merged