Feat/22/activity log
IT-Academy-Social-Projects-KRV/MilitaryManager pull request #29
Opened 2022-10-07 20:52 UTC by Zhykovskiy

2022-10-09 18:01 UTC, vladtymo requested changes

2022-10-09 18:01 UTC, vladtymo commented on MilitaryManager.Infrastructure/Data/MilitaryManagerDbContext.cs
> +            modelBuilder.Entity<ChangeType>().HasData(
Move the data seeding to a separate methods.

2022-10-10 09:32 UTC, vladtymo approved these changes

2022-10-10 13:17 UTC, Alex-knu approved these changes

2022-10-11 06:52 UTC, Alex-knu approved these changes

2022-10-11 07:18 UTC, merged