Feat/3/shared components
IT-Academy-Social-Projects-KRV/MilitaryManager pull request #3
Opened 2022-08-26 22:09 UTC by mershalova

added layout(header footer sidebar themes)

2022-09-06 10:01 UTC, vladtymo requested changes

2022-09-06 10:01 UTC, vladtymo commented on MilitaryManager.Attachments.API/Properties/launchSettings.json
>  }
Add the line break.

2022-09-06 10:01 UTC, vladtymo commented on MilitaryManager/client-app/src/app/app-routing.module.ts
> +// const routes: Routes = [
Remove these comments. We should clean up the code in the PR.

2022-09-06 10:01 UTC, vladtymo commented on MilitaryManager/client-app/src/app/components/home/home.component.spec.ts
> +import { ComponentFixture, TestBed } from '@angular/core/testing';
Delete the spec.ts files as we don't use unit tests.

2022-09-06 10:01 UTC, vladtymo commented on docker-compose.override.yml
> -      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
Revert the configurations to the previous values or configure for MacOS separately.

2022-09-07 06:14 UTC, vladtymo approved these changes

2022-09-07 12:00 UTC, 5haki6 commented on MilitaryManager/client-app/src/app/app-routing.module.ts
> +  children:[
bad aligment

2022-09-07 12:10 UTC, 5haki6 approved these changes

2022-09-08 06:42 UTC, merged