Added view for divisions creating
IT-Academy-Social-Projects-KRV/MilitaryManager pull request #38
Opened 2022-10-18 20:36 UTC by Zhykovskiy

2022-10-20 08:26 UTC, vladtymo requested changes
Let's use the reactive form.

2022-10-24 15:23 UTC, vladtymo commented on MilitaryManager/client-app/src/app/shared/services/core/http.service.ts
> +            .get(`${path}`,  { headers: this.setHeaders(), params })
What was the reason to make these changes?

2022-10-24 15:23 UTC, vladtymo commented on MilitaryManager/client-app/src/app/modules/division-module/pages/division-new/division-new.component.ts
> +      this.useRedClass = false;
Where do you use this property?

2022-10-24 15:50 UTC, Zhykovskiy commented on MilitaryManager/client-app/src/app/shared/services/core/http.service.ts
> +            .get(`${path}`,  { headers: this.setHeaders(), params })
These are changes from branch 78. I'll wait for it's merge before my merge.

2022-10-24 15:53 UTC, Zhykovskiy commented on MilitaryManager/client-app/src/app/modules/division-module/pages/division-new/division-new.component.ts
> +      this.useRedClass = false;
Deleted it.

2022-10-24 16:52 UTC, vladtymo approved these changes

2022-10-25 05:39 UTC, Alex-knu approved these changes

2022-10-25 06:29 UTC, merged