Feat/net097 46/implement a unit commander profile
IT-Academy-Social-Projects-KRV/MilitaryManager pull request #41
Opened 2022-10-20 16:48 UTC by 5haki6

2022-10-20 18:44 UTC, Alex-knu requested changes

2022-10-20 18:44 UTC, Alex-knu commented on MilitaryManager.Units.API/appsettings.json
> +    "DefaultConnection": "Data Source=localhost,1433;Initial Catalog=Units;User ID=sa;Password=password1;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;Mult
remove

2022-10-20 18:44 UTC, Alex-knu commented on MilitaryManager/client-app/src/app/components/profile/profile/profile.component.ts
> +  position: string | null | undefined = '';
?

2022-10-20 18:44 UTC, Alex-knu commented on MilitaryManager/client-app/src/app/components/profile/profile/profile.component.ts
> +              // @ts-ignore
?

2022-10-20 18:44 UTC, Alex-knu commented on MilitaryManager/client-app/src/app/layout/app.menu.component.ts
> +               label: 'Профіль',
conect to icon on top

2022-10-20 19:05 UTC, Alex-knu requested changes

2022-10-20 19:05 UTC, Alex-knu commented on MilitaryManager/client-app/src/app/components/profile/profile/profile.component.ts
> +              this.footSize = this.unitModel?.profiles["0"].value
rewrite like firstOrDefault(item => item.Name == "PropertyName")

2022-10-21 14:05 UTC, Zhykovskiy approved these changes

2022-10-25 06:25 UTC, vladtymo commented on MilitaryManager/client-app/src/app/components/profile/profile/profile.component.ts
> +
Remove empty lines.

2022-10-26 06:13 UTC, Alex-knu approved these changes

2022-10-26 06:13 UTC, Alex-knu commented on MilitaryManager.Core/DTO/Units/UnitDTO.cs
> +        //public List<ProfileDTO> Profiles { get; set; }
Remove comments

2022-10-26 06:47 UTC, merged