Feat/2/Statement Managment
IT-Academy-Social-Projects-KRV/MilitaryManager pull request #5
Opened 2022-08-31 12:22 UTC by NataliaHerus

Tech-dept solution of implementing statement managment

2022-09-05 05:50 UTC, vladtymo approved these changes

2022-09-05 05:50 UTC, vladtymo commented on MilitaryManager/client-app/src/app/shared/state.service.ts
> +}
Add the line break;

2022-09-06 14:35 UTC, Zakerman110 requested changes

2022-09-06 14:35 UTC, Zakerman110 commented on MilitaryManager/client-app/src/app/shared/services/attachments-state.service.ts
> +  units$: Observable<AttachmentModel[]>= this.select(state => state.attachments).pipe(
Rename `units$` to `attachments$`

2022-09-06 14:35 UTC, Zakerman110 commented on MilitaryManager/client-app/src/app/shared/services/api/unit.service.ts
> +  getAll(): Observable<UnitModel[]> {
No need to create `getAll()` method, it is already implemented in BaseService. As a result not need for 14th and 19th lines

2022-09-06 14:35 UTC, Zakerman110 commented on MilitaryManager/client-app/src/app/shared/services/unit-state.service.ts
> +    this.apiService.getAll().subscribe((units) => this.setState({ units}));
You can use already implemented method `this.apiService.collection.getAll().subscribe((units) => this.setState({ units}));`

2022-09-07 07:17 UTC, Zakerman110 approved these changes

2022-09-08 11:27 UTC, YevheniiVovk commented on MilitaryManager.Attachments.API/Properties/launchSettings.json
> +}
End of file

2022-09-08 11:27 UTC, YevheniiVovk commented on MilitaryManager.IdentityServer/Controllers/AccountController.cs
> +					//}
Why it commented ?

2022-09-08 11:27 UTC, YevheniiVovk commented on MilitaryManager.IdentityServer/IdentityConfig.cs
> +
Empty line with spaces

2022-09-08 11:27 UTC, YevheniiVovk commented on MilitaryManager.IdentityServer/Program.cs
> -
Why did you remove this and actually how it connect with your task

2022-09-08 11:27 UTC, YevheniiVovk commented on MilitaryManager.Attachments.API/Properties/launchSettings.json
> +}
Empty line

2022-09-08 11:27 UTC, YevheniiVovk commented on MilitaryManager.IdentityServer/Properties/launchSettings.json
> +}
Empty line

2022-09-08 11:27 UTC, YevheniiVovk commented on MilitaryManager.Units.API/Properties/launchSettings.json
> +}
Empty line

2022-09-08 11:27 UTC, YevheniiVovk commented on MilitaryManager/Properties/launchSettings.json
> +}
Empty line

2022-09-08 11:27 UTC, YevheniiVovk commented on docker-compose.override.yml
> +      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
Empty line

2022-09-08 14:59 UTC, merged