Feat/net097 70/update profile
IT-Academy-Social-Projects-KRV/MilitaryManager pull request #57
Opened 2022-10-28 07:30 UTC by 5haki6

2022-10-29 08:05 UTC, Zakerman110 commented on MilitaryManager.Units.API/appsettings.Development.json
> +    "DefaultConnection": "Data Source=localhost,1433;Initial Catalog=Units;User ID=User_2;Password=qwe123qwe;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;
Please, don't use user and password for local connection, it's just enough for Windows Authentication (integrated security)

2022-10-29 08:05 UTC, Zakerman110 commented on MilitaryManager/client-app/src/app/components/profile/profile/profile.component.ts
> +              private _unitService: UnitsService,
No need to inject every service apart, you can inject only ApiService that includes all other services

2022-10-29 08:05 UTC, Zakerman110 commented on docker-compose.override.yml
> +      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=Units;User ID=User_2;Password=qwe123qwe;MultipleActiveResultSets=true;Application Name=MilitaryManager.Units.API
Don't change docker-compose

2022-10-29 08:05 UTC, Zakerman110 commented on docker-compose.override.yml
> +      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=IdentityServer_AspNet_Identity;User ID=User_2;Password=qwe123qwe;MultipleActiveResultSets=true;Application Name=Ident
Don't change docker-compose

2022-10-31 08:15 UTC, Alex-knu approved these changes

2022-11-01 07:18 UTC, vladtymo requested changes

2022-11-01 07:18 UTC, vladtymo commented on MilitaryManager/client-app/src/app/components/profile/update-profile/update-profile.component.ts
> +      if(control.value < 40 || control.value > 150) {
Move these validator methods to a separate class.

2022-11-01 08:18 UTC, vladtymo requested changes
Add an opportunity to create and remove custom attributes.

2022-11-01 08:36 UTC, vladtymo approved these changes

2022-11-01 08:40 UTC, merged