Feat/83/execute decree operation
IT-Academy-Social-Projects-KRV/MilitaryManager pull request #58
Opened 2022-10-29 18:46 UTC by Zakerman110

Ability to transfer soldiers between divisions according to decree

2022-10-30 12:04 UTC, Alex-knu requested changes

2022-10-30 12:04 UTC, Alex-knu commented on MilitaryManager.Core/Entities/TemplatePlaceholderEntity/TemplatePlaceholder.cs
> +            List<TemplatePlaceholder> placeholders = new List<TemplatePlaceholder>()
Move data to Seed file

2022-10-30 12:04 UTC, Alex-knu commented on MilitaryManager.Core/Entities/TemplatePlaceholderEntity/TemplatePlaceholder.cs
> +        public List<TemplatePlaceholder> GetTemplatePlaceholders()
use db

2022-10-30 12:05 UTC, Zhykovskiy approved these changes

2022-10-30 12:14 UTC, Alex-knu requested changes

2022-10-30 12:14 UTC, Alex-knu commented on MilitaryManager.Core/Entities/UnitEntity/Units.cs
> +                Query.Where(x => x.FirstName == firstName || x.LastName == lastName || x.SecondName == secondName);
use &&

2022-10-31 07:53 UTC, Alex-knu requested changes

2022-10-31 07:53 UTC, Alex-knu commented on MilitaryManager.Core/Entities/DecreeDataEntity/DecreeDatas.cs
> +                Query.Where(x => x.TemplatePlaceholderId == firstNameId && x.DecreeId == decreeId ||
(x.TemplatePlaceholderId == firstNameId || x.TemplatePlaceholderId == lastNameId || x.TemplatePlaceholderId == secondNameId || x.TemplatePlaceholderId == divisionNumberId)  && x.DecreeId == decreeId

2022-10-31 08:19 UTC, Alex-knu approved these changes

2022-10-31 08:19 UTC, merged