Feat/net097 6 1/add unit schema
IT-Academy-Social-Projects-KRV/MilitaryManager pull request #6
Opened 2022-09-03 09:21 UTC by Alex-knu

Added schema for Unit(added to unlock task "(NET097-21)[Architecture] Make a solution for activity log")

2022-09-05 07:50 UTC, vladtymo requested changes

2022-09-05 07:50 UTC, vladtymo commented on MilitaryManager.Core/Entities/UnitEntity/Unit.cs
> +        public List<Soldier> Soldiers { get; set; } = new List<Soldier>();
I think it's better to use ICollection type for navigation prop and HashSet as an instance.

2022-09-05 07:50 UTC, vladtymo commented on MilitaryManager.Core/Entities/SoldierEntity/Soldier.cs
> +        public int? PatronymicId { get; set; }
Change the name to more appropriate.

2022-09-06 09:44 UTC, vladtymo approved these changes

2022-09-06 09:44 UTC, vladtymo commented on MilitaryManager.Core/Entities/AttributeEntity/Attribute.cs
> +    [Table("Attribute", Schema = "Unit")]
Pluralize the table names.

2022-09-08 11:32 UTC, YevheniiVovk commented
At total let's split to 2 PR's 
First one should contains only unit 
Second ione should contains all scheme parts

2022-09-08 11:33 UTC, YevheniiVovk commented on MilitaryManager.Core/DTO/Units/UnitDTO.cs
> +        public virtual ICollection<UnitDTO> SubUnits { get; set; }
What difference between virtual and not virtual navigation properties 
Are we sure that we need to use virtual properties

2022-09-08 11:33 UTC, YevheniiVovk commented on MilitaryManager.Core/Interfaces/IBaseEntity.cs
> +}
We should not use empty interface

2022-09-08 11:33 UTC, YevheniiVovk commented on MilitaryManager.Core/Entities/EntityEntity/Entity.cs
> +    }
IBaseEntity is empty, what a reason to implement empty interface

2022-09-08 11:33 UTC, YevheniiVovk commented on MilitaryManager.Core/Entities/EntityToAttributeEntity/EntityToAttribute.cs
> +        public virtual Attribute Attribute { get; set; }
Same here

2022-09-08 11:38 UTC, YevheniiVovk commented on docker-compose.override.yml
> +      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=IdentityServer_AspNet_Identity;User ID=alex;Password=P@ssw0rd1;MultipleActiveResultSets=true;Application Name=Identit
DO NOT COMMIT changes in docker compose

2022-09-08 11:38 UTC, YevheniiVovk commented on MilitaryManager.Core/Entities/UnitEntity/Units.cs
> +}
Empty line

2022-09-08 11:38 UTC, YevheniiVovk commented on MilitaryManager.Core/Entities/UnitEntity/Unit.cs
> +}
Empty line

2022-09-08 11:38 UTC, YevheniiVovk commented on MilitaryManager.Core/Entities/UnitEntity/Unit.cs
> +        public virtual ICollection<Unit> SubUnits { get; set; }
What difference between virtual and not virtual navigation properties.

2022-09-08 11:38 UTC, YevheniiVovk commented on MilitaryManager.Core/Entities/SoldierEntity/Soldier.cs
> +        public virtual ICollection<Soldier> SubSoldiers { get; set; }
What difference between virtual and not virtual navigation properties.

2022-09-08 17:56 UTC, closed without merging